name: calendar_flutter_test
description: "A customizing of flutter table_calendar."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dotted_decoration: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.1
  table_calendar: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - data/
